### ISSUE TITLE
TeX only 

### ISSUE THREAD

**Issue by nkrusch** [aubertc/au_ccs_dissertation_template#3]
I do not see a reason to support pandoc/markdown version. I believe it is a fair assumption that anyone using this template is familiar with LaTeX. Having these two approaches makes the development and maintenance of this project more complicated in this early stage, where many changes should be anticipated. Please consider streamlining to "tex only".

**Comment by aubertc** [comment]
[PDF are outdated ways of circulating scientific discoveries](https://a3nm.net/work/research/wrong/#PDF) (cf. also [this interesting initiative](https://ar5iv.labs.arxiv.org/)) and LaTeX can only output pdfs.

I would like to encourage students and colleagues to switch to a format (for instance, markdown) that they can re-use to produce website, slides, etc. easily.
The workflow you will adopt when writing your MS / PhD thesis is likely to become the flow you will use your entire professional life: let's try to get it right.

Plus: it's not "disallowed" to use TeX only, and pandoc does some very fine tweakings to standard LaTeX classes that I believe benefit this template.

Also, 

> I believe it is a fair assumption that anyone using this template is familiar with LaTeX. 

this template was originally developed with possible MS students in a potential IT program. I don't think learning LaTeX is a good use of their time, but they may get tired of word: this seems like a sweet spot (once they set-up their system properly…).

**Comment by nkrusch** [comment]
Your intentions are good and reasoning is valid. However, I will add one more comment. 

I opened this with similarly positive intentions, but from a different perspective. I anticipate this template will need a lot of changes once it reaches a state of being actively in use. Then, having two modes will always take longer to implement fixes/enhancements, because changes are being made in two places (I assume?).  

Note, _"...possible MS students in a potential IT program"_, sounds a lot like like future-proofing. I am a bit skeptical of the average general willingness to make that switch, especially for such a big writing task. Change is gradual and starts with small steps. Also, pandoc is great! I use it all the time, just would not use it for this specific purpose. Because this is a big writing task, I want the most powerful writing tools, and minimize the time spent on editing/learning/adjusting anything tech stack-related.
  
I suggested this in an effort to reduce the burden/time sink I expect this template will become, but OK, the response is justified.

**Comment by aubertc** [comment]
Sorry, this should have been clearer:

>  Then, having two modes will always take longer to implement fixes/enhancements, because changes are being made in two places (I assume?).

No, the .tex is generated automatically by pandoc:

https://github.com/aubertc/au_ccs_dissertation_template/blob/eee928f8d559160573dbb151b3b7ff328a12c784/md_version/makefile#L38-L43
